### ISSUE TITLE
lack of cgal library

### ISSUE THREAD

**Issue by handsomeli1898** [rsy6318/PUGeoNet_pytorch#1]
when I evaluate the model, I run into this issue, error with pugeo_pytorch/evaluation/p2f/evaluation: error while loading shared libraries: libCGAL.so.13: cannot open shared object file: No such file or directory. Is it because of the lack of cgal library? If so, how to install it?

**Comment by rsy6318** [comment]
In the Ubuntu OS, you can install cgal through 'sudo apt-get install libcgal-dev'.
Besides, you can also use pymesh to calculate p2f.
