### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Taousst** [rsy6318/PUGeoNet_pytorch#3]
Hello, how do I get the dataset? I ran the code and I got an empty dataset.

**Comment by rsy6318** [comment]
download mesh data from https://drive.google.com/drive/folders/1n2lf4am9k3hy3ci4W20XiMkXwJKwyg8f?usp=sharing
then run the code to prepare data and you would get pc data for training and testing.

**Comment by rsy6318** [comment]
There may be some small changes about the code for preparing data.
